export default defineEventHandler(async (event) => {
  // Read logo from Nitro server assets (works on Vercel + local)
  let logoBase64: string | null = null
  try {
    const logoRaw = await useStorage('assets:server').getItemRaw<Buffer>('logo.png')
    if (logoRaw) logoBase64 = Buffer.from(logoRaw).toString('base64')
  } catch { /* logo not found, skip */ }
  const body = await readBody(event)
  const { pocket_id, pocket_name, strategy_label, asset_symbol, apy, current_value, profit } = body

  if (!pocket_id) {
    throw createError({ statusCode: 400, message: 'Missing pocket_id' })
  }

  const supabase = useServerSupabase()

  const { data: transactions, error } = await supabase
    .from('transactions')
    .select('*')
    .eq('pocket_id', pocket_id)
    .order('timestamp', { ascending: false })

  if (error) throw createError({ statusCode: 500, message: error.message })

  const txs = transactions ?? []

  function formatDate(ts: number): string {
    return new Date(ts * 1000).toLocaleDateString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const typeLabels: Record<string, string> = {
    deposit: 'Deposit',
    withdraw: 'Withdraw',
    redeem: 'Redeem',
  }

  // Dynamic imports to avoid Nitro bundling issues
  const { jsPDF } = await import('jspdf')
  const { default: autoTable } = await import('jspdf-autotable')

  const doc = new jsPDF()

  // Header with logo
  if (logoBase64) {
    doc.addImage(`data:image/png;base64,${logoBase64}`, 'PNG', 14, 10, 12, 12)
    doc.setFontSize(18)
    doc.text('Nestora', 28, 18)
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text('Transaction History', 28, 24)
  } else {
    doc.setFontSize(18)
    doc.text('Nestora', 14, 20)
    doc.setFontSize(10)
    doc.setTextColor(120)
    doc.text('Transaction History', 14, 27)
  }

  // Pocket info
  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.text(pocket_name || 'Pocket', 14, 36)
  doc.setFontSize(9)
  doc.setTextColor(100)
  doc.text(`${strategy_label || ''} Strategy  |  ${asset_symbol || ''}  |  APY: ${apy || 'N/A'}`, 14, 43)
  doc.text(`Current Value: ${current_value || '$0.00'}  |  Profit: ${profit || '$0.00'}`, 14, 49)

  // Table
  const rows = txs.map((tx: any) => [
    formatDate(tx.timestamp),
    typeLabels[tx.type] ?? tx.type,
    `${tx.type === 'deposit' ? '+' : '-'}${tx.amount} ${tx.asset_symbol || asset_symbol || ''}`,
    tx.tx_hash ? tx.tx_hash.slice(0, 10) + '...' + tx.tx_hash.slice(-6) : '',
  ])

  autoTable(doc, {
    startY: 56,
    head: [['Date', 'Type', 'Amount', 'TX Hash']],
    body: rows.length > 0 ? rows : [['No transactions yet', '', '', '']],
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [34, 124, 82], textColor: 255 },
    alternateRowStyles: { fillColor: [245, 245, 245] },
  })

  // Footer
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(7)
  doc.setTextColor(150)
  doc.text('Generated by Nestora  |  nestora.app  |  Built on Base', 14, pageHeight - 10)

  const pdfBuffer = doc.output('arraybuffer')

  setResponseHeaders(event, {
    'Content-Type': 'application/pdf',
    'Content-Disposition': `attachment; filename="${(pocket_name || 'pocket').replace(/\s+/g, '_')}_transactions.pdf"`,
  })

  return send(event, Buffer.from(pdfBuffer))
})
